routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use App\Models\Product;
//use App\Models\SpecialProduct;

Route::get('/', function () {

    return view('auth.login');
});


Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    // return what you want
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('itfail');
//general routes
Route::get('resetpassword','GeneralController@resetPasswordForm')->name('general.resetpasswordform');
Route::post('resetpassword','GeneralController@resetPassword')->name('general.resetpassword');

Route::post('addproduct/discount','GeneralController@addDiscountProduct')->name('general.product.add');
Route::post('updateproduct/discount/{slug}','GeneralController@updateDiscountProduct')->name('general.product.update');

Route::post('addproduct/special','GeneralController@addSpecialProduct')->name('general.product.addspecial');
Route::post('updateproduct/special/{slug}','GeneralController@updateSpecialProduct')->name('general.product.updatespecial');

Route::get('deleteproduct/special/{slug}','GeneralController@deleteSpecialProduct')->name('general.product.deletespecial');




     Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware'=>'admin'],function(){

         Route::get('dashboard','AdminController@dashboard')->name('admin');
         Route::get('users','AdminController@mobileuser')->name('admin.users');
         Route::get('storeusers','AdminController@storeusers')->name('admin.users.store');
         Route::get('storebranchusers/{slug}','AdminController@storeBranchUsers')->name('admin.users.storebranch.users');

         Route::post('adduser','AdminController@addUser')->name('admin.user.add');
         Route::post('adduser/update/{slug}','AdminController@updateUser')->name('admin.user.update');
         Route::get('user/delete/{slug}','AdminController@deleteuser')->name('admin.user.delete');
         //permission
         Route::get('permission','AdminController@allpermission')->name('admin.permission');
         Route::post('permission','AdminController@addNewPermission')->name('admin.permission.add');
         Route::get('permission/edit/{id}','AdminController@editPermission')->name('admin.permission.edit');
         Route::post('permission/update/{id}','AdminController@updatePermission')->name('admin.permission.update');
         Route::get('permission/delete{id}','AdminController@destroyPermission')->name('admin.permission.delete');

         Route::get('resetpassword','AdminController@resetPassword')->name('admin.resetpassword');




         //Role
         Route::get('role','AdminController@allroles')->name('admin.role');
         Route::post('role','AdminController@addNewRole')->name('admin.role.add');
         Route::get('role/edit/{id}','AdminController@editRole')->name('admin.role.edit');
         Route::post('role/update/{id}','AdminController@updateRole')->name('admin.role.update');
         Route::get('role/delete{id}','AdminController@destroyRole')->name('admin.role.delete');


         //store
         Route::get('stores','StoreController@allstores')->name('admin.store.all');//list all store
         Route::get('stores/pending','StoreController@pendingStores')->name('admin.store.pending');//list of pending stores
         Route::get('stores/activated','StoreController@storedetail')->name('admin.store.activated');//activated store
         Route::post('stores','StoreController@addStore')->name('admin.store.add');//add stores
         Route::get('stores/edit/{id}','StoreController@editStore')->name('admin.store.edit');
         Route::post('stores/update/{slug}','StoreController@updateStore')->name('admin.store.update');
         Route::get('stores/activate/{slug}','StoreController@activateStore')->name('admin.store.activate');
         Route::get('stores/deactivate/{slug}','StoreController@deactivateStore')->name('admin.store.deactivate');
         //storebranches
         Route::get('stores/branches/{slug}','StoreController@storebranchesAndUsers')->name('admin.store.branches');
         Route::post('stores/branches','StoreController@createstorebranch')->name('admin.store.createstorebranch');
         Route::post('stores/branches/update/{slug}','StoreController@updateStoreBranch')->name('admin.store.updatestorebranch');
         Route::get('stores/branches/delete/{slug}','StoreController@deleteStoreBranch')->name('admin.store.deletestorebranch');

         Route::post('stores/users','StoreController@createStoreBranchUser')->name('admin.store.createstoreuser');
         Route::post('stores/users/update/{slug}','StoreController@updateStoreBranchUser')->name('admin.store.updatestoreuser');
         Route::get('stores/users/delete/{slug}','StoreController@deleteStoreUser')->name('admin.store.deletestoreuser');
            //store product
         Route::get('stores/product/{slug}','StoreController@storeproduct')->name('admin.store.products');
         Route::post('stores/product/{slug}','StoreController@addStoreProduct')->name('admin.store.addproduct');
         Route::get('stores/product/remove/{slug}','StoreController@removeProduct')->name('admin.store.removeproduct');

         //branches product
         Route::post('stores/branch/product/add','StoreController@addProduct')->name('admin.store.branch.addproduct');
         Route::post('stores/branch/product/update/{slug}','StoreController@updateProduct')->name('admin.store.branch.updateproduct');
         Route::get('stores/branches/loadproduct/{branchid}/{categoryid}','StoreController@loadProductsByCategory');



        //category
        Route::get('categories','CategoryController@index')->name('admin.category.all');
        Route::post('categories','CategoryController@store')->name('admin.category.add');
        Route::get('category/edit/{id}','CategoryController@edit')->name('admin.category.edit');
        Route::post('category/update/{slug}','CategoryController@update')->name('admin.category.update');
        Route::get('category/{slug}','CategoryController@destroy')->name('admin.category.delete');

        //products
         Route::get('products','ProductController@allproduct')->name('admin.product.all');
         Route::get('products/pending','ProductController@pendingProduct')->name('admin.product.pending');
         Route::get('products/deal','ProductController@dealProduct')->name('admin.product.deal');

         Route::post('products','ProductController@storeProduct')->name('admin.product.add');
         Route::get('product/edit/{slug}','ProductController@editProduct')->name('admin.product.edit');
         Route::post('product/update/{slug}','ProductController@updateProduct')->name('admin.product.update');
         Route::get('product/delete/{slug}','ProductController@deleteProduct')->name('admin.product.delete');

         Route::get('product/approve/{slug}','ProductController@approveCreateProduct')->name('admin.product.approve');


         Route::get('product/activate/{slug}','ProductController@activateProduct')->name('admin.product.activate');
         Route::get('product/deactivate/{slug}','ProductController@deactivateProduct')->name('admin.product.deactivate');


         Route::get('adverts','AdvertController@alladverts')->name('admin.alladvert');
         Route::post('adverts','AdvertController@addAdvert')->name('admin.advert.add');
         Route::post('advert/{slug}/update','AdvertController@updateAdvert')->name('admin.advert.update');
         Route::get('adverts/delete/{slug}','AdvertController@deleteAdvert')->name('admin.advert.delete');



         Route::get('banners','AdvertController@allbanners')->name('admin.allbanner');
         Route::post('banners','AdvertController@addBanner')->name('admin.banner.add');
         Route::post('banner/{slug}/update','AdvertController@updateBanner')->name('admin.banner.update');
         Route::get('banner/delete/{slug}','AdvertController@deleteBanner')->name('admin.banner.delete');
     });

    Route::group(['prefix'=>'store', 'namespace'=>'Store', 'middleware'=>'store'],function(){
        Route::get('dashboard', 'StoreController@dashboard')->name('store');

        Route::post('setupstore', 'StoreController@setupStore')->name('store.setupstore');
        Route::post('addbranchadmin', 'StoreController@addStoreBranchAdmin')->name('store.addadmin');

        Route::post('setupbranch', 'StoreController@setUpBranch')->name('store.setupbranch');
        Route::get('branchdetail/{slug}', 'StoreController@branchDetail')->name('store.branchdetail');

        //products
        Route::get('branchdetail/branches/loadproduct/{branchid}/{categoryid}','StoreController@loadProductsByCategory');
        Route::post('branches/products/add','StoreController@addBranchProduct')->name('store.branch.addproduct');
        Route::post('branch/product/update/{slug}','StoreController@updateProduct')->name('store.branch.updateproduct');




        Route::get('branchuserform', 'StoreController@addBranchUserForm')->name('store.addbranchuserform');
        Route::get('branchuserlist', 'StoreController@allstoreusers')->name('store.branchuserlist');
        Route::post('addbranchadmincont', 'StoreController@addStoreBranchAdminSecond')->name('store.addadminsecond');

        Route::post('storeuser/update/{slug}','StoreController@updatestoreuser')->name('store.user.update');
        Route::get('storeuser/delete/{slug}','StoreController@deleteUser')->name('store.user.delete');
        Route::get('unassigneduser/{slug}', 'StoreController@detachedUserFromBranch')->name('store.user.detachedUser');

app/Models/Product.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Cviebrock\EloquentSluggable\Sluggable;

class Product extends Model
{
    use Sluggable;
    use SoftDeletes;
    protected $date = ['deleted_at'];
    protected $fillable = ['categoryid','createproductid', 'storeproductid', 'storeid','storebranchid','productname','quantity','price','measurementid','dealprice','dealstatus','dealpercentage', 'lowestdiscout',  'dealexpire','measurement','size','views','slug'];
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'productname'
            ]
        ];
    }
/*
 * Relationship
 */
    public function category(){
        return $this->belongsTo(Category::class,'categoryid');
    }
    public function createproduct(){
        return $this->belongsTo(CreateProduct::class,'createproductid');
    }
    public function store(){
        return $this->belongsTo(Store::class,'storeid');
    }
    public function storebranch(){
        return $this->belongsTo(StoreBranch::class,'storebranchid');
    }

    public function dealalert(){
        return $this->hasMany(DealAlert::class,'productid');
    }
    public function productorder(){
        return $this->hasMany(ProductOrder::class,'productid');
    }
    public function storeproduct(){
        return $this->belongsTo(StoreProduct::class,'storeproductid');
    }

    /*
     * Operations
     */
    public function getProductNameAttribute(){
        return ucwords($this->attributes['productname']);
    }
    public function setProductStatusAttribute(){
        $today = Carbon::now();
        if($this->attributes['dealexpire'] > $today){
            $this->attributes['dealstatus'] = 1;
        }else{
            $this->attributes['dealstatus'] =0;
        }


    }

}

app/Models/Store.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Cviebrock\EloquentSluggable\Sluggable;
use Auth;

class Store extends Model
{
    use Sluggable;
    use SoftDeletes;
    protected $date = ['deleted_at'];
    protected $fillable = ['store_name','store_image','store_address','store_status','store_lat','store_long','views','slug','totalproducts','lowestdiscout'];
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'store_name'
            ]
        ];
    }
    /*
     * Relationship
     */
    public function storebranch(){
        return $this->hasMany(StoreBranch::class,'storeid');
    }
    public function product(){
        return $this->hasMany(Product::class,'storeid');
    }

    public function user(){
        return $this->belongsTo(User::class,'userid');
    }
    public function storeproduct(){
        return $this->hasMany(StoreProduct::class,'storeid');
    }
    public function storeuser(){
        return $this->hasMany(StoreUser::class,'storeid');
    }
    public function advert(){
        return $this->hasMany(Advert::class,'advert_sponsor');
    }
    public function banner(){
        return $this->hasMany(Banner::class,'storeid');
    }
    public function specialproduct(){
        return $this->hasMany(SpecialProduct::class,'storeid');
    }
    /*
     * operation
     */
    public function getStoreNameAttribute(){
        return ucwords($this->attributes['store_name']);
    }
    public function storeid(){
        $userid = Auth::user()->id;
        $storeid = $this->userid == $userid ? $this->id : 0;
        return $storeid;
    }

}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Product;
use App\Models\SpecialProduct;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function tenOnGoingDeal(){
        $today = Carbon::now();
        $deals = Product::with('storebranch','store','category')->where('dealexpire','>',$today)->inRandomOrder()->take(9)->get();
        return response()->json($deals,200);
    }

    public function hotdeals(){
            $today = Carbon::now();
            $deals = Product::with('storebranch','store','category')->where('dealexpire','>',$today)->where('dealpercentage','>=',40)->inRandomOrder()->get();
            return response()->json($deals,200);
    }

    public function latestdeals(){
        $today = Carbon::now();
        $deals = Product::with('storebranch','store','category')->orderByDesc('updated_at')->where('dealexpire','>',$today)->get();
        return response()->json($deals,200);
    }


    public function onGoingDeals(){
        $today = Carbon::now();
        $deals = Product::with('storebranch','store','category')->where('dealexpire','>',$today)
            ->inRandomOrder()->get();
        return response()->json($deals,200);
    }

    public function productDetail($id){
        $products = Product::with('store','storebranch')->findOrFail($id);
        return response()->json($products,200);
    }
    public function searchProduct($product){
        $today = Carbon::now();
        $search = str_replace(' ','',strtolower($product));
        $products = Product::with('storebranch','category','store')->where('dealexpire','>',$today)->where('productname','like','%'.$search.'%')->get();
        return response()->json($products,200);
    }

    public function allProductsFromStoreBranches($storeid){
        $today = Carbon::now();
        $products = Product::with('storebranch','store','category')->where(['storeid'=>$storeid])->where('dealexpire','>',$today)->inRandomOrder()->get();
        return response()->json($products,200);
    }

    public function hotDealByCategory($categoryid){
        $today = Carbon::now();
        $products = Product::with('storebranch','store','category')->where(['categoryid'=>$categoryid])->where('dealexpire','>',$today)
            ->where('dealpercentage','>=',40)
            ->inRandomOrder()->get();
        return response()->json($products,200);
    }
    public function latestDealByCategory($categoryid){
        $today = Carbon::now();
        $products = Product::with('storebranch','store','category')->where(['categoryid'=>$categoryid])->where('dealexpire','>',$today)
            ->orderByDesc('updated_at')->get();
        return response()->json($products,200);
    }

    public function hotDealByStore($storeid){
        $today = Carbon::now();
        $products = Product::with('storebranch','store','category')->where(['storeid'=>$storeid])->where('dealexpire','>',$today)
            ->where('dealpercentage','>=',40)
            ->inRandomOrder()->get();
        return response()->json($products,200);
    }
    public function latestDealByStore($storeid){
        $today = Carbon::now();
        $products = Product::with('storebranch','store','category')->where(['storeid'=>$storeid])->where('dealexpire','>',$today)
            ->orderByDesc('updated_at')->get();
        return response()->json($products,200);
    }


    public function allSpecialProductsFromStoreBranches($storeid){
        $today = Carbon::now();
        $products = SpecialProduct::with('storebranch','store','category')->where(['storeid'=>$storeid])->where('offerexpire','>',$today)->inRandomOrder()->get();
        return response()->json($products,200);
    }


}

resources/views/store/products/addproduct.blade.php
@extends('layouts.backend')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-light breadcrumb-custom bg-inverse-primary">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{url()->previous()}}">{{@$store->store_name}}</a></li>
            <li class="breadcrumb-item active" aria-current="All Listed users">All Listed Users</li>
        </ol>
    </nav>


    <form action="{{route('store.product.add')}}" method="post">
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="row">
                <div class="col-md-6 float-left">
                    @if(!empty($toBeAddedproducts))
                        <div class="row">
                            <div class="col-md-1">
                                <input id="allproduct" type="checkbox" class="btn btn-primary text-white">
                            </div>
                            <div class="col-md-3 pull-left"><h4>Check all</h4></div>
                            <div class="col-md-8"></div>
                        </div>

                    @else
                    @endif
                </div>
                <div class="col-md-6 float-right">

                    @if(!empty($toBeAddedproducts))
                        <button type="submit" class="btn btn-primary text-white pull-right" ><i
                                    class="ti-pencil-alt"></i> Save Selections
                        </button>


                        {{--<input type="submit" value="save" class="btn btn-success">--}}
                    @else
                    @endif
                </div>
                <div class="col-12 col-xl-7">
                    <div class="d-flex align-items-center justify-content-between flex-wrap">
                        <div class="mb-3 mb-xl-0">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">


                        {{csrf_field()}}
                    <div class="table-responsive">
                        <table id="order-listing" class="table">
                            <thead>
                            <tr class="bg-primary text-white">
                                <th>S/N #</th>
                                <th>Product Name</th>
                                <th>Categody</th>
                                <th>Product Image</th>
                                <th>Check</th>
                            </tr>
                            </thead>
                            <tbody>

                            @if(!empty($toBeAddedproducts))

                                    @forelse($toBeAddedproducts as $t)
                                       <tr>
                                           <td>{{$loop->iteration}}</td>
                                           <td>{{$t->product_name}}<i id="icon_check" class="ti-check icon-check" style="display: none"></i></td>
                                           <td>{{$t->category->category_name}}</td>
                                           <td><div style="background-image: url('{{$t->product_image}}');width:100px;height: 100px;"></div></td>
                                           <td>
                                                   <input type="checkbox" id="singlecheck" name="createproductid[]" class="form-control" value="{{$t->id}}">
                                               </td>
                                       </tr>
                                        @empty
                                        <h3 class="text-center">No New Products</h3>
                                    @endforelse


                            @else
                                <h3 class="text-center">No New Products</h3>
                            @endif


                            </tbody>
                        </table>
                    </div>


                </div>
            </div>
    </form>

        </div>

    </div>
    <script>
        $(document).ready(function(){
            $("#allproduct").click(function(){
                $('input:checkbox').not(this).prop('checked', this.checked);
                $('.icon-check').toggle();
            });
            $("#singlecheck").on('change',function(){
                $('#icon-check').show();
            })
        });
    </script>
    <style>
        .icon-check{
            margin: 0 10px;
            font-size: 20px;
            border: 5px;
            color: green;
        }
        input[type='checkbox'] {
            -webkit-appearance:none;
            width:30px;
            height:30px;
            background:white;
            border-radius:5px;
            border:2px solid #555;
        }
        input[type='checkbox']:checked {
            background: green;
            border: 5px solid green;
        }

    </style>



 @endsection